#device: fc\raid\ethernet\infiniband testcase need configuration, It is obtained from the OECH command line interface and
#        needs to be enclosed in single quotation marks
#disk: fc\raid\disk testcase need configuration, The disk to be tested, such as sda; Or all, test all qualified disks.
#if_rdma: ethernet testcase need configuration, N means to test according to ordinary network card, y means to test according to RDMA card
#server_ip: ethernet and infiniband needs configuration, The IP address of the server needs to be
#           configured manually and can be pinged，

fc:
  fc1:
    device: '0000:03:00.0'
    disk: all
  fc2:
    device: '0000:03:00.1' 
    disk: sda
raid:
  raid1:
    device: '0000:02:00.0'
    disk: all
  raid2:
    device: '0000:0a:00.1'
    disk: sdb
disk: all
ethernet:
  eth1:
    device: enp125s0f0
    if_rdma: N
    server_ip: 127.0.0.1
  eth2:
    device: enp125s0f1
    if_rdma: N
    server_ip: 127.0.0.1
infiniband:
  ib1:
    device: ibp1s0
    server_ip: 127.0.0.1
  ib2:
    device: ibp1s0
    server_ip: 127.0.0.1 
    

