#device: fc\raid\ethernet\infiniband testcase need configuration, It is obtained from the OECH command line interface and
#        needs to be enclosed in single quotation marks
#disk: fc\raid\disk testcase need configuration, The disk to be tested, such as sda; Or all, test all qualified disks.
#if_rdma: ethernet testcase need configuration, N means to test according to ordinary network card, y means to test according to RDMA card
#server_ip: ethernet\infiniband testcase need configuration. If the server port is modified, need to add the port number after the IP address. eg: 2.2.2.4:8090.
#          User need to delete the ip manually which are configured by tool after testing.
#clent_ip: ethernet\infiniband testcase need configuration. IP to be configured for the client port
fc:
  fc1:
    device: '0000:03:00.0'
    disk: all
  fc2:
    device: '0000:03:00.1' 
    disk: sda
raid:
  raid1:
    device: '0000:02:00.0'
    disk: all
  raid2:
    device: '0000:0a:00.1'
    disk: sdb
disk: all
ethernet:
  # IP has been manually configured, get server IP.
  eth1:
    device: enp125s0f0
    if_rdma: N
    client_ip:
    server_ip: 2.2.2.4
  # Configure the IP obtained here.
  eth2:
    device: enp125s0f1
    if_rdma: N
    client_ip: 2.2.2.3
    server_ip: 2.2.2.4
  # The program automatically generates an IP address for IP configuration
  eth3:
    device: enp125s0f2
    if_rdma: y
    client_ip:
    server_ip:
infiniband:
  # IP has been manually configured, get server IP.
  ib1:
    device: ibp1s0
    client_ip:
    server_ip: 2.2.2.4
  # Configure the IP obtained here.
  ib2:
    device: ibp1s0
    client_ip: 2.2.2.3
    server_ip: 2.2.2.4:8090
  # The program automatically generates an IP address for IP configuration
  ib3:
    device: ibp1s0
    client_ip:
    server_ip:
    

